name: CI

on: [push, pull_request]
env:
  XCODE_VER: 12.4

jobs:
  build:
    strategy:
      matrix:
        xcode_version: ['12.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Set branch name
        run: git config --global init.defaultBranch main 
      - name: Check out Swift 
        uses: actions/checkout@v2
      - name: update-checkout
        run: |
          set -euo pipefail
          git checkout main
          ./utils/update-checkout --clone
          git checkout github-actions
