name: CI

on: [push, pull_request]
env:
  XCODE_VER: 12.4

jobs:
  build:
    strategy:
      matrix:
        xcode_version: ['12.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out Swift 
        uses: actions/checkout@v2
      - name: update-checkout
        run: |
          set -euo pipefail
          git fetch origin
          git checkout main
          ./utils/update-checkout --clone
          git checkout github-actions
      - name: Build & Test
        run: utils/build-script --skip-build-benchmarks --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" --release-debuginfo --swift-disable-dead-stripping --test
